<?php

namespace ContainerBuc37l9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_P9I88zFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.p9I88zF' shared service.
     *
     * @return \App\Controller\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\OwnerController::index()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?');
    }
}
