vich_uploader:
  db_driver: orm
  # mappings:
  #   files:
  #     uri_prefix: "%app.path.files%"
  #     upload_destination: "%kernel.project_dir%/public%app.path.files%"
  #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
