<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJOoxYbD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJOoxYbD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJOoxYbD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJOoxYbD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJOoxYbD\App_KernelDevDebugContainer([
    'container.build_hash' => 'JOoxYbD',
    'container.build_id' => '8e82d84b',
    'container.build_time' => 1673305189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJOoxYbD');
