<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTO0qdIh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTO0qdIh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTO0qdIh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTO0qdIh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTO0qdIh\App_KernelDevDebugContainer([
    'container.build_hash' => 'TO0qdIh',
    'container.build_id' => 'c0d5dfe0',
    'container.build_time' => 1673950304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTO0qdIh');
